### ISSUE TITLE
HTTP Error 400.

### ISSUE THREAD

**Issue by sigainey** [Dictionarry-Hub/profilarr#139] opened 2024-11-08 19:43 UTC
### Dictionarry Issue Report Format

**Title of Issue:** Http Error 400

**Description:**
Setup on Windows 11 using Python 3.13. edited config.yml with API key for both the single instances of radare and sonar.

**Environment:**
- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Radarr/Sonarr Version:** [Specify the version you are using]
- **Profilarr Version (if applicable):** 

**Profile Used (if applicable):**
- **Profile Name:** [e.g., 1080p x264 Encode, 4K remux]

**Steps to Reproduce:**
Ran python syncarr.py

**Expected Behavior:**
No 400 error

**Actual Behavior:**
See below

**Screenshots/Logs:**
C:\profilarr-0.3.2.1>python importarr.py
Select your app of choice
1. radarr
2. sonarr
Enter your choice:
2
Select your Sonarr instance
1. Sonarr (Master)
Choose an instance by number, multiple numbers separated by commas or type 'all' for all instances:
1

Importing custom formats to Sonarr : Master

Updating custom format 'D-Z0N3' : SUCCESS
Updating custom format 'DON' : SUCCESS
Updating custom format 'EbP' : SUCCESS
Updating custom format 'Geek' : SUCCESS
Updating custom format 'TayTo' : SUCCESS
Updating custom format 'ZQ' : SUCCESS
Updating custom format 'VietHD' : SUCCESS
Updating custom format 'CtrlHD' : SUCCESS
Updating custom format 'HiFi' : SUCCESS
Updating custom format 'FoRM' : SUCCESS
Updating custom format 'HiDt' : SUCCESS
Updating custom format 'SA89' : SUCCESS
Updating custom format 'CRiSC' : SUCCESS
Updating custom format 'NTb' : SUCCESS
Updating custom format 'decibeL' : SUCCESS
Updating custom format 'NCmt' : SUCCESS
Updating custom format 'de[42]' : SUCCESS
Updating custom format 'IDE' : SUCCESS
Updating custom format 'HDMaNiAcS' : SUCCESS
Updating custom format 'LolHD' : SUCCESS
Updating custom format 'BMF' : SUCCESS
Updating custom format 'EA' : SUCCESS
Updating custom format 'TBB' : SUCCESS
Updating custom format 'nmd' : SUCCESS
Updating custom format 'SbR' : SUCCESS
Updating custom format 'PTer' : SUCCESS
Updating custom format 'Dariush SD' : SUCCESS
Updating custom format 'TDD' : SUCCESS
Updating custom format 'Penumbra' : SUCCESS
Updating custom format 'FTW-HD' : SUCCESS
Updating custom format 'xander' : SUCCESS
Updating custom format 'Chotab' : SUCCESS
Updating custom format 'ESiR' : SUCCESS
Updating custom format 'Positive' : SUCCESS
Updating custom format 'ORiGEN' : SUCCESS
Updating custom format 'SaNcTi' : SUCCESS
Updating custom format 'ThD' : SUCCESS
Updating custom format 'ZIMBO' : SUCCESS
Updating custom format 'NyHD' : SUCCESS
Updating custom format 'luvBB' : SUCCESS
Updating custom format 'GALAXY' : SUCCESS
Updating custom format 'HiP' : SUCCESS
Updating custom format 'GS88' : SUCCESS
Updating custom format 'W4NK3R' : SUCCESS
Updating custom format 'SiMPLE' : SUCCESS
Updating custom format 'BV' : SUCCESS
Updating custom format 'GutS' : SUCCESS
Updating custom format 'E.N.D' : SUCCESS
Updating custom format 'playHD' : SUCCESS
Updating custom format 'WMING' : SUCCESS
Updating custom format 'KASHMiR' : SUCCESS
Updating custom format 'c0ke' : SUCCESS
Updating custom format 'HANDJOB' : SUCCESS
Updating custom format 'EDPH' : SUCCESS
Updating custom format 'MTeam' : SUCCESS
Updating custom format 'iFT' : SUCCESS
Updating custom format 'FraMeSToR' : SUCCESS
Updating custom format 'LEGi0N' : SUCCESS
Updating custom format 'BHDStudio' : SUCCESS
Updating custom format '1080p' : SUCCESS
Updating custom format '720p' : SUCCESS
Updating custom format '2160p' : SUCCESS
Updating custom format 'Blu-Ray' : SUCCESS
Updating custom format 'WEBRip' : SUCCESS
Updating custom format 'x264' : SUCCESS
Updating custom format 'REMUX' : SUCCESS
Updating custom format 'Amazon Prime' : SUCCESS
Updating custom format 'Movies Anywhere' : SUCCESS
Updating custom format 'Apple TV+' : SUCCESS
Updating custom format 'Disney+' : SUCCESS
Updating custom format 'HBO Max' : SUCCESS
Updating custom format 'Netflix' : SUCCESS
Updating custom format 'Hulu' : SUCCESS
Updating custom format 'Peacock TV' : SUCCESS
Updating custom format 'Paramount+' : SUCCESS
Updating custom format 'iTunes' : SUCCESS
Updating custom format 'DD+' : SUCCESS
Updating custom format 'DTS' : SUCCESS
Updating custom format 'DD' : SUCCESS
Updating custom format 'ATMOS' : SUCCESS
Updating custom format 'IMAX' : SUCCESS
Updating custom format 'x265' : SUCCESS
Updating custom format 'DTS-HD MA' : SUCCESS
Updating custom format 'FLAC' : SUCCESS
Updating custom format 'DTS-X' : SUCCESS
Updating custom format 'TrueHD' : SUCCESS
Updating custom format 'Black and White' : SUCCESS
Updating custom format 'RightSIZE' : SUCCESS
Updating custom format 'Unwanted' : SUCCESS
Updating custom format '3D' : SUCCESS
Updating custom format 'Disc ' : SUCCESS
Updating custom format 'BeyondHD' : SUCCESS
Updating custom format 'ROKU' : SUCCESS
Updating custom format 'iTunes (Missing)' : SUCCESS
Updating custom format 'HANDJOB SD' : SUCCESS
Updating custom format 'DVD REMUX ' : SUCCESS
Updating custom format 'DVD' : SUCCESS
Updating custom format 'Xvid' : SUCCESS
Updating custom format 'TBB SD' : SUCCESS
Updating custom format 'Dariush ' : SUCCESS
Updating custom format '480p' : SUCCESS
Updating custom format 'Extras' : SUCCESS
Updating custom format 'VVC' : SUCCESS
Updating custom format 'AV-1' : SUCCESS
Updating custom format 'mHD' : SUCCESS
Updating custom format 'Scene' : SUCCESS
Updating custom format 'LoRD' : SUCCESS
Updating custom format 'Stream Optimised' : SUCCESS
Updating custom format 'HDR10+' : SUCCESS
Updating custom format 'Dolby Vision' : SUCCESS
Updating custom format 'HDR10' : SUCCESS
Updating custom format 'HDR10 (Missing)' : SUCCESS
Updating custom format 'TrueHD (Missing)' : SUCCESS
Updating custom format 'ATMOS (Missing)' : SUCCESS
Updating custom format 'UHDBits' : SUCCESS
Updating custom format 'Dolby Vision w/out Fallback' : SUCCESS
Updating custom format '3L' : SUCCESS
Updating custom format 'TRiToN' : SUCCESS
Updating custom format 'WiLDCAT' : SUCCESS
Updating custom format 'PmP' : SUCCESS
Updating custom format 'BLURANiUM' : SUCCESS
Updating custom format 'playBD' : SUCCESS
Updating custom format 'EPSiLON' : SUCCESS
Updating custom format 'LQ' : SUCCESS
Updating custom format 'CJ' : SUCCESS
Updating custom format 'pcroland' : SUCCESS
Updating custom format 'BTN' : SUCCESS
Updating custom format 'iON' : SUCCESS
Updating custom format 'AJP69' : SUCCESS
Updating custom format 'VLAD' : SUCCESS
Updating custom format 'hdalx' : SUCCESS
Updating custom format 'LiNG' : SUCCESS
Updating custom format 'h265' : SUCCESS
Updating custom format 'Blu-Ray (Remux)' : SUCCESS
Updating custom format 'PCM' : SUCCESS
Updating custom format 'h265 (4k)' : SUCCESS
Updating custom format 'MAX' : SUCCESS
Updating custom format 'HR' : SUCCESS

Successfully added 0 custom formats, updated 138 custom formats.

Available profiles:
1. 1080p Balanced (Single Grab) (sonarr - master).json
2. 1080p Balanced (sonarr - master).json
3. 1080p h265 Balanced  (sonarr - master).json
4. 1080p h265 Balanced (Single Grab) (sonarr - master).json
5. 1080p Optimal (Single Grab) (sonarr - master).json
6. 1080p Optimal (sonarr - master).json
7. 1080p Transparent (Double Grab) (sonarr - master).json
8. 1080p Transparent (Single Grab) (sonarr - master).json
9. 1080p Transparent (sonarr - master).json
10. 2160p Optimal (Single Grab) (sonarr - master).json
11. 2160p Optimal (sonarr - master).json

Enter the numbers of the profiles you want to import separated by commas, or type 'all' to import all profiles:
2
Importing Quality Profiles to sonarr : Master

HTTP Error 400.
Adding '1080p Balanced' quality profile : FAIL

**Additional Context:**
[Include any other information that might be useful for troubleshooting, such as recent changes to your setup or specific settings.]
Not had it running yet, this is my first go. If I type all to import all profiles, it gives multiple errors

**Comment by santiagosayshey** [comment] 2024-11-09 01:01
hi @sigainey, could you share your sonarr log after attempting import?

Cheers

**Comment by sigainey** [comment] 2024-11-09 07:46
2024-11-09 07:43:33.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
2024-11-09 07:43:33.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
2024-11-09 07:43:33.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
2024-11-09 07:43:33.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
2024-11-09 07:43:33.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
2024-11-09 07:43:33.5|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
2024-11-09 07:43:33.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
2024-11-09 07:43:33.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
2024-11-09 07:43:33.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
2024-11-09 07:43:33.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
2024-11-09 07:43:33.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities




About
Version 4.0.10.2544
.NET Yes (6.0.13)
Database Sqlite 3.36.0
Database Migration 215
AppData Directory C:\ProgramData\Sonarr
Startup Directory C:\ProgramData\Sonarr\bin
Mode Service
Uptime 1d 17:30:37

**Comment by santiagosayshey** [comment] 2024-11-09 08:17
Ah yep, the issue is you're trying to import outdated profiles on a newer sonarr version. See here for more details: https://github.com/Dictionarry-Hub/profilarr/commit/8be921cab90e25879f95330fb484b4d9716b860e

You'll need to grab the latest release from here: https://github.com/Dictionarry-Hub/profilarr/releases/tag/v0.3.2.2 and try again.

That should fix it up, but just let me know if anything else breaks. Closing this for now!

**Closed by santiagosayshey** 2024-11-09 08:17 UTC

**Comment by sigainey** [comment] 2024-11-09 12:33
Yes mate, this worked a treat, thank you for looking at it and doing this project in the first place

**Comment by Qrrbrbirlbel** [comment] 2025-01-25 01:36
I'm using the most recent version of Profilarr and I get the same error message. Indeed, the profiles I'm trying to import are over half a year old.

Do I need to update the json files?

**Comment by santiagosayshey** [comment] 2025-01-30 19:17
> I'm using the most recent version of Profilarr and I get the same error message. Indeed, the profiles I'm trying to import are over half a year old.
> 
> Do I need to update the json files?

hi, yes you do.

**Comment by Wendigogo** [comment] 2025-02-10 14:27
Hi,
Sorry to pup-up this issue again but I got the same problem :
```
Importing custom formats to Sonarr : Master

Adding custom format 'ATMOS (undefined)' : SUCCESS
Adding custom format 'DTS-HD MA' : SUCCESS
Adding custom format 'HDR10+' : SUCCESS
Adding custom format 'x264' : SUCCESS
Adding custom format 'DV HDR10' : SUCCESS
Adding custom format 'AV1' : SUCCESS
Adding custom format 'TrueHD' : SUCCESS
Adding custom format 'x265' : SUCCESS
Adding custom format 'DD+ ATMOS' : SUCCESS
Adding custom format 'DTS X' : SUCCESS
Adding custom format 'Surround Sound' : SUCCESS
Adding custom format 'Multi-French' : SUCCESS
HTTP Error 400.
Adding custom format 'French Audio' : FAILHTTP Error 400.
Adding custom format 'REPACK x264' : FAILHTTP Error 400.
Adding custom format 'REPACK x265' : FAILHTTP Error 400.
Adding custom format 'VOST' : FAILHTTP Error 400.
Adding custom format 'VOSTFR' : FAILAdding custom format 'HDR' : SUCCESS
Adding custom format 'TEAM' : SUCCESS
Adding custom format 'Size 2GB' : SUCCESS
```
and I don't understand what I have to do in json file...

I'm on latest version of Sonarr (v4.0.12.2900).

Thanks for your help.

**Comment by santiagosayshey** [comment] 2025-02-10 22:40
Glad you got it sorted :)

**Comment by Qrrbrbirlbel** [comment] 2025-02-11 10:21
> > I'm using the most recent version of Profilarr and I get the same error message. Indeed, the profiles I'm trying to import are over half a year old.
> > Do I need to update the json files?
> 
> hi, yes you do.

I've added the Bluray-576p item to all JSONs and I'm still getting the 400 error.
````
{
    "quality": {
        "id": 22,
        "name": "Bluray-576p",
        "source": "bluray",
        "resolution": 576
    },
    "items": [],
    "allowed": true
}
````

But it also doesn't properly import all Custom Formats … maybe the backup was too old because I can't even import a custom format manually as Sonarr reports "Unknown option '0' for condition 'Release Title'".

At least I still have the backup so I can add the formats manually.

**Comment by santiagosayshey** [comment] 2025-02-12 00:28
> > > I'm using the most recent version of Profilarr and I get the same error message. Indeed, the profiles I'm trying to import are over half a year old.
> > > Do I need to update the json files?
> > 
> > hi, yes you do.
> 
> I've added the Bluray-576p item to all JSONs and I'm still getting the 400 error.
> ````
> {
>     "quality": {
>         "id": 22,
>         "name": "Bluray-576p",
>         "source": "bluray",
>         "resolution": 576
>     },
>     "items": [],
>     "allowed": true
> }
> ````
> 
> But it also doesn't properly import all Custom Formats … maybe the backup was too old because I can't even import a custom format manually as Sonarr reports "Unknown option '0' for condition 'Release Title'".
> 
> At least I still have the backup so I can add the formats manually.

You dont need to update the files manually yourself, you just need to download the latest json files.

**Comment by santiagosayshey** [comment] 2025-02-14 11:08
Right, it wasn’t clear that you were interacting your own custom files, not the dictionarry ones. 

You define the folder you want to import from inside your config file, and put your files inside there. The default is `/import`.

As for why things aren’t importing correctly, it’s hard to say without seeing the full logs. If it’s possible, I’d suggest downgrading your sonarr/radarr version down to whatever you exported from then importing again. Then you can upgrade again.

**Comment by Qrrbrbirlbel** [comment] 2025-02-15 13:57
> Right, it wasn’t clear that you were interacting your own custom files, not the dictionarry ones.

Sorry about that. I assumed that my case is the default one.

> As for why things aren’t importing correctly, it’s hard to say without seeing the full logs.

Ah, right. Sonarr logs! With my original files I get

```
2025-02-15 13:35:05.4|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- MinUpgradeFormatScore: 'Min Upgrade Format Score' must be greater than or equal to '1'.
 -- Items: Must contain all qualities
```

I've added both `"minUpgradeFormatScore": 1` and the Bluray-576p quality and now the importarr doesn't raise any errors anymore!

**Comment by santiagosayshey** [comment] 2025-02-15 15:19
> I've added both `"minUpgradeFormatScore": 1` and the Bluray-576p quality and now the importarr doesn't raise any errors anymore!

Awesome, glad you got it working :)
